### ISSUE TITLE
Support for Linux

### ISSUE THREAD

**Issue by jack-jun** [stereolabs/zed-unreal-plugin#5]
Hi,

Is there any plan to support Linux/Ubuntu platform(AArch 64)?

**Comment by obraun-sl** [comment]
Hi,
Currently there is no plans on our side to have a Linux compatibility for the plugin.

**Comment by Tetsujinfr** [comment]
Hi, any update on having unreal plugin supported for linux / aarch64?

**Comment by Tetsujinfr** [comment]
Can you point on which source files would have to be adapted to get it working on Linux? Given the sdk is operational for aarch64, I assume one could try to modify the plugin source code to get it working?

**Comment by obraun-sl** [comment]
You also need to build the custom engine for aarch64. 
As far as I know, they might be some issue since the build of the engine calls unreal softwares that might not be available on aarch64. 
We tried to do it some years ago but did not succeed. However, it might have change since.

**Comment by Tetsujinfr** [comment]
Yes, I have built the UE4.23 engine successfully for jetson, that works fine.
So wondering if I just need to do it again but with the 4.21 zed branch + having the zed sdk installed on jetson or if I would need to modify some additional code. 

I am going to give it a try and let you know how that went.  But ideally I would like to get it working for a more recent version than 4.21. Also I need to mix it with other third party code which have to build from source, like google resonnance, which have their own UE from source version requirements.
Thanks

**Comment by Tetsujinfr** [comment]
Ok after quite some time and challenges I ended up successfully compiling UE4.21.2 Stereolabs version, along the Zed unreal plugin and the ZED UE4 examples, on windows. Took my 2 days of compiling and re-compiling!
**So glad I made it though, the examples are really cool!!!**

Btw, I initially tried my luck with the latest SDK available, i.e. 3.4.2 as of now, and the engine compiled ok however when I tried running the passthrough example (or any example) the example would start, the camera led would turn blue, but no image would appear. So no crash, no error message, but just no image, all dark. Then I re-installed the SDK 3.0.3 which is the one that the current ZED UE4 Plugin version expects I think, and after 2h of compilation time, all did work well.
**It would be great if you can check that the latest SDK works ok with the plugin, it seems to me the issue might be minor but that would save a ton of time and you enable me to benefit from the latest SDK improvements too.**

-> Now the main challenge for me, get all that to compile on the Jetson properly.
So when exporting for the Linux plateform, I have suprisingly very few errors, only 3 as per VS (only 2 different ones I think):

> UATHelper: Packaging (Linux):     In file included from D:/Projects/unreal/UE4_Examples/Intermediate/Build/Linux/93821A52/ZEDSamples/Development/Renderer/Module.Renderer.7_of_12.cpp:13:
> UATHelper: Packaging (Linux):     D:\Unreal\UnrealEngine-4.21-zed\Engine\Source\Runtime\Renderer\Private\PostProcess\PostProcessVirtualObjects.cpp(274,47):  error: reference to type 'const FGlobalShaderPermutationParameters' could not bind to an lvalue of type 'EShaderPlatform'
> UATHelper: Packaging (Linux):                     FGlobalShader::ModifyCompilationEnvironment(Platform, OutEnvironment);
> UATHelper: Packaging (Linux):                                                                 ^~~~~~~~
> UATHelper: Packaging (Linux):     D:/Unreal/UnrealEngine-4.21-zed/Engine/Source/Runtime/ShaderCore/Public\GlobalShader.h(161,100):  note: passing argument to parameter 'Parameters' here
> UATHelper: Packaging (Linux):             SHADERCORE_API static void ModifyCompilationEnvironment(const FGlobalShaderPermutationParameters& Parameters, FShaderCompilerEnvironment& OutEnvironment) {}
> UATHelper: Packaging (Linux):                                                                                                               ^
> UATHelper: Packaging (Linux):     In file included from D:/Projects/unreal/UE4_Examples/Intermediate/Build/Linux/93821A52/ZEDSamples/Development/Renderer/Module.Renderer.7_of_12.cpp:13:
> UATHelper: Packaging (Linux):     D:\Unreal\UnrealEngine-4.21-zed\Engine\Source\Runtime\Renderer\Private\PostProcess\PostProcessVirtualObjects.cpp(339,1):  error: template specialization requires 'template<>'
> UATHelper: Packaging (Linux):     IMPLEMENT_SHADER_TYPE(, FPostProcessBlurVirtualObjectsPS<EFP_Horiz>, TEXT("/Engine/Private/PostProcessBlurVirtualObjects.usf"), TEXT("BlurVirtualObjectsPS"), SF_Pixel);
> UATHelper: Packaging (Linux):     ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> UATHelper: Packaging (Linux):                             template<>
> UATHelper: Packaging (Linux):     D:/Unreal/UnrealEngine-4.21-zed/Engine/Source/Runtime/ShaderCore/Public\Shader.h(1128,43):  note: expanded from macro 'IMPLEMENT_SHADER_TYPE'
> UATHelper: Packaging (Linux):             ShaderClass::ShaderMetaType ShaderClass::StaticType( \
> UATHelper: Packaging (Linux):                                         ~~~~~~~~~~~  ^
> UATHelper: Packaging (Linux):     In file included from D:/Projects/unreal/UE4_Examples/Intermediate/Build/Linux/93821A52/ZEDSamples/Development/Renderer/Module.Renderer.7_of_12.cpp:13:
> UATHelper: Packaging (Linux):     D:\Unreal\UnrealEngine-4.21-zed\Engine\Source\Runtime\Renderer\Private\PostProcess\PostProcessVirtualObjects.cpp(340,1):  error: template specialization requires 'template<>'
> UATHelper: Packaging (Linux):     IMPLEMENT_SHADER_TYPE(, FPostProcessBlurVirtualObjectsPS<EFP_Vert>, TEXT("/Engine/Private/PostProcessBlurVirtualObjects.usf"), TEXT("BlurVirtualObjectsPS"), SF_Pixel);
> PackagingResults: Error: reference to type 'const FGlobalShaderPermutationParameters' could not bind to an lvalue of type 'EShaderPlatform'
> UATHelper: Packaging (Linux):     ^                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> UATHelper: Packaging (Linux):                             template<>
> UATHelper: Packaging (Linux):     D:/Unreal/UnrealEngine-4.21-zed/Engine/Source/Runtime/ShaderCore/Public\Shader.h(1128,43):  note: expanded from macro 'IMPLEMENT_SHADER_TYPE'
> UATHelper: Packaging (Linux):             ShaderClass::ShaderMetaType ShaderClass::StaticType( \
> UATHelper: Packaging (Linux):                                         ~~~~~~~~~~~  ^
> UATHelper: Packaging (Linux):     3 errors generated.

**Any chance you can help me debug this or point me toward the right direction?** The errors seem to be related to some platform export configs or definitions but not sure where to go. It is going to take me a lot of time to parse the modified engine renderer code (if I ever make it there).

thanks

Edit: regarding the first error, I attach the file Module.Renderer.7_of_12.cpp, where line 13 corresponds to PostProcessVirtualObjects.cpp (as indicated by VS):

- #include "D:\Unreal\UnrealEngine-4.21-zed\Engine\Source\Runtime\Renderer\Private\PostProcess\PostProcessVirtualObjects.cpp"

[Module.Renderer.7_of_12.zip](https://github.com/stereolabs/zed-unreal-plugin/files/6208477/Module.Renderer.7_of_12.zip)

Edit2: I am under Win10, 16Gb RAM, using VS2017.

Edit3: I tried to package for Win64 to check if it works but the packaging kind of failed too: the build has been successful but the cooking step failed due to some error "LogInit: Warning: Incompatible or missing module: ZEDSamples". The exe is generated in the binaries folder though, I can launch it, it works but crashes when I close the ZEDSamples.exe windows (some mem realloc error). So a bit messy so far on Windows as well for me. So I wonder: are the examples packageable? Did anyone do that and has it been confirmed it works for Windows at least?
Edit4: the win64 cooking arreor is actually `UATHelper: Packaging (Windows (64-bit)):   LogWindows: Error: Assertion failed: !PinRef->bWasTrashed [File:D:\Unreal\UnrealEngine-4.21-zed\Engine\Source\Runtime\Engine\Private\EdGraph\EdGraphPin.cpp] [Line: 1845]`. Seems to be a common error as per unreal error tickets logs, but I am not brave enough yet to start cleaning up all my intermediate/saved/config folders for an unwarranted result.

**Comment by Tetsujinfr** [comment]
Hi Olivier

Please give can you give me a quick hint on where to look at about the `Platform` and the `EShaderPlatform` lvalue binding error above, so that I can work on it over the WE?

I suspect there is some hard coded win64 platform somewhere but not sure.
Is there a documentation on the Unreal stereolabs plugin I can look at somewhere? Or I must go through the all code base and parse it?

Really appreciate your help on this, it is critical for me.

Merci d'avance.

Edit: I attach the full log file in case it helps to better pinpoint the issue. I have added the below in the Config\DefaultEngine.ini file btw for the Linux Aarch64 build:
```
[/Script/LinuxTargetPlatform.LinuxTargetSettings]
TargetArchitecture=AArch64UnknownLinuxGnueabi
```
[UBT-ZEDSamples-Linux-Development.zip](https://github.com/stereolabs/zed-unreal-plugin/files/6217743/UBT-ZEDSamples-Linux-Development.zip)

**Comment by obraun-sl** [comment]
@Tetsujinfr 
Sorry for late reply. I will try to find some time this week to check it

**Comment by Tetsujinfr** [comment]
Thanks. I have tried a few quick changes this WE but unsuccessfully.
I saw there is the plugin build.cs file which checks that targetplateform.win64 is true so maybe this is the reason but I am not sure. I did not try to modify that yet.

**Comment by obraun-sl** [comment]
Yes, you will need to modify that part by adding the path relatively to the platform.
You also need to modify the whitelistplatform in the .uplugin : 
https://github.com/stereolabs/zed-unreal-plugin/blob/master/Stereolabs/Stereolabs.uplugin#L23

**Comment by Tetsujinfr** [comment]
Did you have a chance to look at what it would take to get the zed plugin to work under aarch64?

For now I am looking at the `Stereolabs.build.cs` file and trying to add a Linux target platform set of conditions.
So first, I need to come up with a path for the ZED SDK location, similar to the one in the env variable "ZED_SDK_ROOT_DIR" under Windows: **is there such a variable under Linux when the SDK is being installed?**. I could not find any so far, e.g. I have looked at the .bashrc config file but did not see any environment variable related to the ZED SDK there: do I need to hard code the path with `/usr/local/zed` if there is no such variable?
For the CudaSDKPath I think I should be good with `CUDADIR` which for me equals `/usr/local/cuda `, but please let me know if you think otherwise.

Then I can see that `Stereolabs.cpp` under `source/private/Stereolabs/` is loading the win64 SDK lib as well as the NVidia OGL/D3D driver api lib `nvd3dumx.dll`: this has to be replaced for aarch64 I assume. For the SDK lib, I guess `libsl_zed.so` would  be the equivalent? What about `nvd3dumx.dll`?

I attach a quick and dirty modified `Stereolabs.build.cs` file:
[Stereolabs.Build.cs.zip](https://github.com/stereolabs/zed-unreal-plugin/files/6251835/Stereolabs.Build.cs.zip)
~~But I got new errors when trying to build the sample project for the Linux Target, e.g. "_ERROR: Unable to instantiate module 'Stereolabs': System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\usr\local\zed\lib'._".~~
Here is the first error I get now when trying to build the project for Linux under UE4 Editor, which seems to be related to a windows specific header file of the plugin, which might not be proved since I did add a Linux target value to the Stereolabs.uplugin file, not sure though:
> D:/Projects/unreal/UE4_Examples/Plugins/Stereolabs/Source\Stereolabs/Public/Core/StereolabsBaseTypes.h(5,10):  fatal error: 'AllowWindowsPlatformTypes.h' file not found
> UATHelper: Packaging (Linux):     #include "AllowWindowsPlatformTypes.h"
> UATHelper: Packaging (Linux):              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

So my lack of understanding of the Unreal plugin flow hurts already. I am not sure if I am going in the right direction really.

I am moving slowly on this given I have no experience on unreal plugins. Your expert help is greatly appreciated.
thanks

_Edit 1: updating the first error description based on a new version of the build.cs file whwre I quick and dirty removed the dependency on "Directory.GetFiles()" to bypass the error and I provided the ZED SDK .so file names directly. I attach the .uplugin file too._
[Stereolabs.uplugin.zip](https://github.com/stereolabs/zed-unreal-plugin/files/6251856/Stereolabs.uplugin.zip)

**Comment by Tetsujinfr** [comment]
Hi Olivier, did you have a chance to look at porting the ZED plugin for AArch64? (Jetson)?

I have some time this week so I am plannong to look at that on my end but I need some help here. Especially with how to connect properly the plugin with the ZED SDK binaries on Jetson and how to cut the dependencies with the Windows one.

 Thanks. This is really critical for my project to get the ZED to work with Unreal/Jetson.

**Comment by obraun-sl** [comment]
No yet, sorry. 
I'll try to find some time at the end of the week.
Did you already build the custom engine ( https://github.com/Stereolabs-Unreal/UnrealEngine/tree/4.21-zed) 
on aarch64?

**Comment by Tetsujinfr** [comment]
I see the plugin requires the Cuda header file to compile. Do you need Cuda for many of the ZED core functionalities (tracking, SLAM, etc) or is it used only for the ZED2 object tracking ?

Asking because I am on ZED mini and I need tracking and SLAM, si if I can remove the cuda dependency for cross compulation of the plugin, I would then try to remove it.

**Comment by obraun-sl** [comment]
Yes, almost all SDK functions require GPU/CUDA (pre-process, depth, tracking, OD)

**Comment by Tetsujinfr** [comment]
Ok thanks. So then I suspect that Cuda cross-compilation has to be managed an dmost likely added to the aarch64 cross compilation toolchain provided by EpicGames. I have seen that nVidia provides cross-compilation tools for Windows to Linux, but I have to look it up in details. With Jetpack 4.4DP, the Cuda version provided is 10.2.89 (so 10.2). Checking their documentation today.

**Comment by Tetsujinfr** [comment]
So under the CUDA 10.2 [documentation](https://docs.nvidia.com/cuda/archive/10.2/cuda-installation-guide-linux/index.html#cross-platform), they mention: `Cross-platform development is only supported on Ubuntu systems` as a host system.

For unreal engine, my understanding is that cross-compilation is only supported with Windows as a host system.

I was thinking to move the host system from Windows x86_64 to Ubuntu x86_64, but Unreal Engine seems to support cross compilation only from a Windows host system (my understanding).

So not clear to me how to cross compile the plugin from Windows for aarch64 as a target with Cuda in the mix. Do you have an idea?

**Comment by Tetsujinfr** [comment]
Ok so I have imported all the cuda header files dependency on my windows machine and the plugin packaging process has continued.
~~Now I have windows related dependencies, specifically at this stage the below headers:~~
~~UATHelper: Packaging (Linux):     D:/Projects/unreal/UE4_Examples/Plugins/Stereolabs/Source\Stereolabs/Public/Core/StereolabsBaseTypes.h(9,10):  fatal error: 'HideWindowsPlatformTypes.h' file not found~~
~~UATHelper: Packaging (Linux):     D:/Unreal/UnrealEngine-4.21-zed/Engine/Source/Runtime/Core/Public\Windows/MinWindows.h(68,10):  fatal error: 'Windows.h' file not found~~

~~Obviously I do not need windows specific functions under Aarch64.~~
~~1) Do you really use those as part of the ZED plugin?~~
~~2) if yes do you have an idea on how to remove those dependencies or replace them with Linux equivalent libs?~~

I managed to get rid of the windows headers dependencies for now, not sure if that will cause me troubles downstream or not yet.

So I got some new errors, where for some reason the packager cannot find `sl_mr_core/defines.hpp`.
`UATHelper: Packaging (Linux):     D:/Projects/unreal/UE4_Examples/Plugins/Stereolabs/Source\Stereolabs/Public/Core/StereolabsCoreGlobals.h(11,10):  fatal error: 'sl_mr_core/defines.hpp' file not found
`

I need to check why that is the case, hopefully defining some dependency folder pointing to _Plugins\Stereolabs\Source\ThirdParty\MixedReality\include\sl_mr_core\defines.hpp_ will do the trick.

Olivier, did you have a chance to look at this as well?

thanks
